### ISSUE TITLE
Voice UI

### ISSUE THREAD

**Issue by tobyclh** [ajsato/HumanInterface2019#1]
**Title** (including conference names and years)
Voice Interfaces in Everyday Life
CHI 2018

**Author and affiliation**
Martin Porcheron*
, Joel E. Fischer*
, Stuart Reeves*
, and Sarah Sharples†
*Mixed Reality Laboratory
School of Computer Science
University of Nottingham, UK
†Human Factors Research Group
Faculty of Engineering
University of Nottingham, UK

**Motivation**
- What problems were they trying to solve?
- What was missing in existing technology?
we don't understand **how** people interact with the voice ui.
this work aims to help the design of conversational interface.

**Method**
- What did they create? How did they justify the system/algorithm/interface design?
- How did they evaluate?
a month-long user study which all conversation with an Amazon Echo is recorded and analysed.

**Insight**
- What did they find? 
- What take-away messages do we have from this work?

**(One-sentence) Contribution Summary**
Summarize their work in a sentence with the following format.
[Author] did [Method] for [Motivation], and found [Insight].

**Comment by tobyclh** [comment]
some random blog post
https://www.nngroup.com/articles/voice-assistant-attitudes/
## Highlight
We usually have no compunction carrying out a conversation with a real person in a public space. Yet this behavior did not apply to intelligent assistants. Users in our study reported a strong preference for using voice assistants only when they were at home or by themselves. Most people said they would not interact with a phone-based agent like Siri or Google Now in a public setting. Some, however, where willing to ask for directions while walking.

One participant phrased this plainly, noting “when I'm in public, I don't usually use [Siri] — I just think it looks a little bit awkward. It also feels awkward to use her in public. I also don't see other people using it in public.”

**Comment by tobyclh** [comment]
[random patent from MS
](https://www.voicesummit.ai/blog/microsofts-silent-technology-lets-you-whisper-voice-commands)
I don't think it will work.
![image](https://user-images.githubusercontent.com/12501995/57589194-9132a580-755b-11e9-8bce-cca678f66e36.png)

**Comment by ajsato** [comment]
## Embedded Speech Recognition Applications in Mobile Phones: Status, Trends, and Challenges
### Jordan Cohen (SRI International)

**Comment by tobyclh** [comment]
let's keep this issue open

**Comment by ajsato** [comment]
I think I accidentally clicked close. Sorry about that.

**Comment by ajsato** [comment]
Tentatively decided to focus on the correlation between chatting and facial expression.
